title: CS HDR Conversion Program
description: Providing Research Pathways to Computer Science Honours and Master by Coursework Students
show_downloads: true
google_analytics:
remote_theme: pages-themes/leap-day@v0.2.0
theme: jekyll-theme-leap-day